wallpaper {
        monitor = HDMI-A-1
        path = /home/luke/Wallpapers/illustration-anime-city3.jpg
        fit_mode = cover
}

wallpaper {
        monitor = HDMI-A-2
        path = /home/luke/Wallpapers/illustration-anime-city3.jpg
        fit_mode = cover
}
